/*      Copyright 2016 Arizona Board of regents on behalf of
 *                  The University of Arizona
 *                     All Rights Reserved
 *         (USE & RESTRICTION - Please read COPYRIGHT file)
 *
 *  Version    : DEVSJAVA 2.7
 *  Date       : 11-12-2016
 *  Authors	   : Scott DeVoge and Scott Litz
 */

package DeVogeLitzMod;

import java.awt.*;

import GenCol.*;


import model.modeling.*;
import model.simulation.*;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;
import view.simView.*;

public class epm extends ViewableDigraph{

	public epm(){
	    super("epm");
	
	    ViewableDigraph eg = new eventGenerator();
	    ViewableAtomic sp = new systemProcessor("sp", 1);
	    ViewableAtomic sm = new systemMonitor("sm", 200);
	
	    add(eg);
	    add(sp);
	    add(sm);
	
	    addInport("in");
	    addInport("start");
	    addInport("stop");
	    addOutport("out");
	    addOutport("result");
	
	    addCoupling(this, "in", eg, "in");
	    addCoupling(this, "start", eg, "start");	    
	    addCoupling(this, "stop", eg, "stop");
	    
	    addCoupling(eg, "out", sp, "in");
	    addCoupling(eg, "out", sm, "ariv");
	    addCoupling(sp, "out", sm, "solved");
	    addCoupling(sm, "out", eg, "stop");
	    
	    addCoupling(sp, "out", this, "out");
	    addCoupling(sm, "out", this, "result");
	}
    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
	public void layoutForSimView()
    {
        preferredSize = new Dimension(591, 369);
        ((ViewableComponent)withName("sm")).setPreferredLocation(new Point(0, 290));
        ((ViewableComponent)withName("sp")).setPreferredLocation(new Point(278, 230));
        ((ViewableComponent)withName("eg")).setPreferredLocation(new Point(70, 50));
    }
}

