/*      Copyright 2016 Arizona Board of regents on behalf of
 *                  The University of Arizona
 *                     All Rights Reserved
 *         (USE & RESTRICTION - Please read COPYRIGHT file)
 *
 *  Version    : DEVSJAVA 2.7
 *  Date       : 11-12-2016
 *  Authors	   : Scott DeVoge and Scott Litz
 */

package DeVogeLitzMod;

import java.awt.*;

import GenCol.*;
import SimpArcMod.genr;
import SimpArcMod.transd;
import model.modeling.*;
import model.simulation.*;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;
import view.simView.*;

public class experimentalFrame extends ViewableDigraph{

	public experimentalFrame(){
	    super("experimentalFrame");
	    experimentalFrameConstruct(1, 12);
	    
	    addTestInput("x", new Pair(new Pair(new entity("1000"), new entity("basic")), new entity("none")));
	}

	public experimentalFrame(String nm, double int_arr_t,double observe_t){
	    super(nm);
	    experimentalFrameConstruct(int_arr_t, observe_t);
	}

	public void experimentalFrameConstruct(double int_arr_t, double observe_t){

	    addInport("in");
	    addInport("x");
	    addOutport("out");
	    addOutport("result");
	    
	    ViewableAtomic g = new generator("g", int_arr_t);
	    ViewableAtomic t = new transducer("t", observe_t);

	    add(g);
	    add(t);
	    
	    initialize();

	    addCoupling(this, "x", g, "in");
	    addCoupling(this, "in", t, "solved");
	    addCoupling(g, "out", t, "arriv");
	    addCoupling(t, "out", g, "stop");
	    addCoupling(g, "out", this, "out");
	    addCoupling(t, "out", this, "result");
	}
    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
	public void layoutForSimView()
    {
		preferredSize = new Dimension(497, 110);
		((ViewableComponent)withName("t")).setPreferredLocation(new Point(10, 31));
        ((ViewableComponent)withName("g")).setPreferredLocation(new Point(220, 31));
    }
}

